import blueBowl from "@/assets/images/blueberry-banana.png";
import greenBowl from "@/assets/images/cucumber-smoothie.png";
import yellowBowl from "@/assets/images/Mango-almond.png";
import purpleBowl from "@/assets/images/purple-hibuscus.png";
import blueBowl2 from "@/assets/images/blue-spirulina.png";
import blueBowl3 from "@/assets/images/blueberry-spiral.png";
import purpleBowl2 from "@/assets/images/Dragon-Fruit-Smoothie.png";
import purpleBowl3 from "@/assets/images/purple-smoothie.png";
import greenBowl2 from "@/assets/images/Green-Smoothie-Bowls.png";
import greenBowl3 from "@/assets/images/kiwi-smothie.png";
import yellowBowl2 from "@/assets/images/mango-smoothie-bowl.png";
import yellowBowl3 from "@/assets/images/mango-smoothie.png";
import pinkBowl from "@/assets/images/berry-smoothie.png";
import pinkBowl2 from "@/assets/images/pink-paradise.png";
import pinkBowl3 from "@/assets/images/strawberry-banana-smoothie.png";

import raspberry from "@/assets/icons/raspberry.svg";
import strawberry from "@/assets/icons/strawberry.svg";
import blueberry from "@/assets/icons/blueberries.svg";
import blueRaspberry from "@/assets/icons/blue-raspberry.svg";
import banana from "@/assets/icons/banana.svg";
import coconut from "@/assets/icons/coconut.svg";
import cucumber from "@/assets/icons/cucumber.svg";
import dragonFruit from "@/assets/icons/dragonfruit.svg";
import mango from "@/assets/icons/mango.svg";
import pineapple from "@/assets/icons/pineapple.svg";
import apple from "@/assets/icons/apple.svg";
import avocado from "@/assets/icons/avocado.svg";
import grapefruit from "@/assets/icons/grapefruit.svg";
import berries from "@/assets/icons/berries.svg";
import kiwi from "@/assets/icons/kiwi.svg";

export const smoothiesList = [
  {
    id: 1,
    src: blueBowl,
    alt: "blueberry bowl",
    borderColor: "border-blue-darker",
    shadowColor: "max-md-tablet:shadow-[0_10px_20px_rgb(100,149,237)]",
    backgroundColor: "bg-blue-darker",
    footerBackgroundColor: "md-tablet:bg-blue-lightest",
    mainBackgroundColor:
      "bg-gradient-to-r from-blue-darker from-50% to-blue-light to-50% ",
    bgFill: "fill-blue-light",
    hoverColor: "hover:bg-blue-light",
    text: "Blueberry Banana Smoothie",
    textColor: "text-blue-darker",
    shadowBtnColor: "shadow-blue-darker",
    logoFill: "fill-blue-darker",
    isFavorite: false,
    className: "",
    content: [blueberry, blueRaspberry],
    nutritionalVal: ["209", "3g", "35g", "14g", "44mg"],
    price: "10.75",
    relatedSmoothies: [2, 3, 1],
  },
  {
    id: 2,
    src: blueBowl2,
    alt: "blue spirulina bowl",
    borderColor: "border-blue-darker",
    shadowColor: "max-md-tablet:shadow-[0_10px_20px_rgb(100,149,237)]",
    backgroundColor: "bg-blue-darker",
    footerBackgroundColor: "md-tablet:bg-blue-lightest",
    mainBackgroundColor:
      "bg-gradient-to-r from-blue-darker from-50% to-blue-light to-50% ",
    bgFill: "fill-blue-light",
    hoverColor: "hover:bg-blue-light",
    text: "Blue Spirulina Smoothie",
    textColor: "text-blue-darker",
    shadowBtnColor: "shadow-blue-darker",
    logoFill: "fill-blue-darker",
    isFavorite: false,
    className: "",
    content: [blueberry, banana, mango, cucumber, strawberry],
    nutritionalVal: ["817", "56.7g", "71.2g", "121.4g", "107.6mg"],
    price: "6.99",
    relatedSmoothies: [1, 3, 2],
  },
  {
    id: 3,
    src: blueBowl3,
    alt: "blueberry spiral bowl",
    borderColor: "border-blue-darker",
    shadowColor: "max-md-tablet:shadow-[0_10px_20px_rgb(100,149,237)]",
    backgroundColor: "bg-blue-darker",
    footerBackgroundColor: "md-tablet:bg-blue-lightest",
    mainBackgroundColor:
      "bg-gradient-to-r from-blue-darker from-50% to-blue-light to-50% ",
    bgFill: "fill-blue-light",
    hoverColor: "hover:bg-blue-light",
    text: "Blueberry Spiral Smoothie",
    textColor: "text-blue-darker",
    shadowBtnColor: "shadow-blue-darker",
    logoFill: "fill-blue-darker",
    isFavorite: false,
    className: "",
    content: [blueberry, blueRaspberry, coconut, dragonFruit],
    nutritionalVal: ["209", "3g", "35g", "14g", "44mg"],
    price: "7.75",
    relatedSmoothies: [1, 2, 3],
  },
  {
    id: 4,
    src: greenBowl,
    alt: "cucumber bowl",
    borderColor: "border-green-darker",
    shadowColor: "max-md-tablet:shadow-[0_10px_20px_rgb(85,107,47)]",
    backgroundColor: "bg-green-darker",
    footerBackgroundColor: "md-tablet:bg-green-lightest",
    mainBackgroundColor:
      "bg-gradient-to-r from-green-darker from-50% to-green-light to-50% ",
    bgFill: "fill-green-light",
    logoFill: "fill-green-darker",
    isFavorite: false,
    hoverColor: "hover:bg-green-light",
    shadowBtnColor: "shadow-green-darker",
    text: "Cucumber Smoothie",
    textColor: "text-green-darker",
    className: "md-tablet:px-8",
    content: [banana, cucumber, pineapple],
    nutritionalVal: ["389", "1.4g", "96.6g", "4.8g", "17.2mg"],
    price: "11.25",
    relatedSmoothies: [5, 6, 4],
  },
  {
    id: 5,
    src: greenBowl2,
    alt: "green berry bowl",
    borderColor: "border-green-darker",
    shadowColor: "max-md-tablet:shadow-[0_10px_20px_rgb(85,107,47)]",
    backgroundColor: "bg-green-darker",
    footerBackgroundColor: "md-tablet:bg-green-lightest",
    mainBackgroundColor:
      "bg-gradient-to-r from-green-darker from-50% to-green-light to-50% ",
    bgFill: "fill-green-light",
    logoFill: "fill-green-darker",
    isFavorite: false,
    hoverColor: "hover:bg-green-light",
    shadowBtnColor: "shadow-green-darker",
    text: "Green Berry Smoothie",
    textColor: "text-green-darker",
    className: "md-tablet:px-8",
    content: [banana, avocado, blueberry, raspberry],
    nutritionalVal: ["310", "15.6g", "41.5g", "7.9g", "171mg"],
    price: "9.99",
    relatedSmoothies: [4, 6, 5],
  },
  {
    id: 6,
    src: greenBowl3,
    alt: "kiwi bowl",
    borderColor: "border-green-darker",
    shadowColor: "max-md-tablet:shadow-[0_10px_20px_rgb(85,107,47)]",
    backgroundColor: "bg-green-darker",
    footerBackgroundColor: "md-tablet:bg-green-lightest",
    mainBackgroundColor:
      "bg-gradient-to-r from-green-darker from-50% to-green-light to-50% ",
    bgFill: "fill-green-light",
    logoFill: "fill-green-darker",
    hoverColor: "hover:bg-green-light",
    shadowBtnColor: "shadow-green-darker",
    isFavorite: false,
    text: "Kiwi Smoothie",
    textColor: "text-green-darker",
    className: "md-tablet:px-8",
    content: [kiwi, banana, avocado, blueberry, coconut],
    nutritionalVal: ["420", "20g", "59g", "8g", "162mg"],
    price: "6.25",
    relatedSmoothies: [4, 5, 6],
  },

  {
    id: 7,
    src: pinkBowl,
    alt: "Berry Strawberry Smoothie",
    borderColor: "border-pink-darker",
    shadowColor: "max-md-tablet:shadow-[0_10px_20px_rgb(223,64,98)]",
    backgroundColor: "bg-pink-darker",
    hoverColor: "hover:bg-pink-light",
    mainBackgroundColor:
      "bg-gradient-to-r from-pink-darker from-50% to-pink-light to-50% ",
    footerBackgroundColor: "md-tablet:bg-pink-lightest",
    bgFill: "fill-pink-lightest",
    logoFill: "fill-pink-darker",
    textColor: "text-pink-darker",
    shadowBtnColor: "shadow-pink-darker",
    text: "Berry-Strawberry Smoothie",
    isFavorite: false,
    className: "",
    content: [strawberry, raspberry],
    nutritionalVal: ["155", "0g", "35g", "5g", "54mg"],
    price: "12.99",
    relatedSmoothies: [8, 9, 7],
  },
  {
    id: 8,
    src: pinkBowl2,
    alt: "Pink Paradise Smoothie",
    borderColor: "border-pink-darker",
    shadowColor: "max-md-tablet:shadow-[0_10px_20px_rgb(223,64,98)]",
    backgroundColor: "bg-pink-darker",
    hoverColor: "hover:bg-pink-light",
    mainBackgroundColor:
      "bg-gradient-to-r from-pink-darker from-50% to-pink-light to-50% ",
    footerBackgroundColor: "md-tablet:bg-pink-lightest",
    bgFill: "fill-pink-lightest",
    logoFill: "fill-pink-darker",
    textColor: "text-pink-darker",
    shadowBtnColor: "shadow-pink-darker",
    text: "Pink Paradise Smoothie",
    isFavorite: false,
    className: "",
    content: [strawberry, apple, berries],
    nutritionalVal: ["270", "9g", "33g", "10g", "0mg"],
    price: "8.99",
    relatedSmoothies: [7, 9, 8],
  },
  {
    id: 9,
    src: pinkBowl3,
    alt: "Strawberry Banana Smoothie",
    borderColor: "border-pink-darker",
    shadowColor: "max-md-tablet:shadow-[0_10px_20px_rgb(223,64,98)]",
    backgroundColor: "bg-pink-darker",
    hoverColor: "hover:bg-pink-light",
    mainBackgroundColor:
      "bg-gradient-to-r from-pink-darker from-50% to-pink-light to-50% ",
    footerBackgroundColor: "md-tablet:bg-pink-lightest",
    bgFill: "fill-pink-lightest",
    logoFill: "fill-pink-darker",
    textColor: "text-pink-darker",
    shadowBtnColor: "shadow-pink-darker",
    isFavorite: false,
    text: "Strawberry Banana Smoothie",
    className: "",
    content: [strawberry, banana],
    nutritionalVal: ["303", "2g", "69g", "3g", "0mg"],
    price: "8.75",
    relatedSmoothies: [7, 8, 9],
  },

  {
    id: 10,
    src: purpleBowl,
    alt: "hibiscus chia bowl",
    borderColor: "border-purple-darker",
    shadowColor: "max-md-tablet:shadow-[0_10px_20px_rgb(128,0,128)]",
    backgroundColor: "bg-purple-darker",
    footerBackgroundColor: "md-tablet:bg-purple-lightest",
    mainBackgroundColor:
      "bg-gradient-to-r from-purple-darker from-50% to-purple-light to-50% ",
    bgFill: "fill-purple-light",
    logoFill: "fill-purple-darker",
    hoverColor: "hover:bg-purple-light",
    shadowBtnColor: "shadow-purple-darker",
    isFavorite: false,
    text: "Hibiscus Chia Smoothie",
    textColor: "text-purple-darker",
    className: "md-tablet:px-5",
    content: [banana, strawberry, dragonFruit],
    nutritionalVal: ["209", "3g", "35g", "14g", "44mg"],
    price: "10.99",
    relatedSmoothies: [11, 12, 10],
  },
  {
    id: 11,
    src: purpleBowl2,
    alt: "dragon fruit bowl",
    borderColor: "border-purple-darker",
    shadowColor: "max-md-tablet:shadow-[0_10px_20px_rgb(128,0,128)]",
    backgroundColor: "bg-purple-darker",
    footerBackgroundColor: "md-tablet:bg-purple-lightest",
    mainBackgroundColor:
      "bg-gradient-to-r from-purple-darker from-50% to-purple-light to-50% ",
    bgFill: "fill-purple-light",
    logoFill: "fill-purple-darker",
    isFavorite: false,
    hoverColor: "hover:bg-purple-light",
    shadowBtnColor: "shadow-purple-darker",
    text: "Dragonfruit Smoothie",
    textColor: "text-purple-darker",
    className: "md-tablet:px-5",
    content: [banana, strawberry, dragonFruit, coconut],
    nutritionalVal: ["260", "10g", "34g", "12g", "44mg"],
    price: "5.99",
    relatedSmoothies: [10, 12, 11],
  },
  {
    id: 12,
    src: purpleBowl3,
    alt: "purple berry bowl",
    borderColor: "border-purple-darker",
    shadowColor: "max-md-tablet:shadow-[0_10px_20px_rgb(128,0,128)]",
    backgroundColor: "bg-purple-darker",
    footerBackgroundColor: "md-tablet:bg-purple-lightest",
    mainBackgroundColor:
      "bg-gradient-to-r from-purple-darker from-50% to-purple-light to-50% ",
    bgFill: "fill-purple-light",
    logoFill: "fill-purple-darker",
    hoverColor: "hover:bg-purple-light",
    isFavorite: false,
    shadowBtnColor: "shadow-purple-darker",
    text: "Purple Berry Smoothie",
    textColor: "text-purple-darker",
    className: "md-tablet:px-5",
    content: [blueberry, raspberry, grapefruit, avocado, apple],
    nutritionalVal: ["209", "3g", "35g", "14g", "44mg"],
    price: "8.99",
    relatedSmoothies: [10, 11, 12],
  },

  {
    id: 13,
    src: yellowBowl,
    alt: "mango almond bowl",
    borderColor: "border-yellow-darker",
    shadowColor: "max-md-tablet:shadow-[0_10px_20px_rgb(240,128,128)]",
    backgroundColor: "bg-yellow-darker",
    footerBackgroundColor: "md-tablet:bg-yellow-lightest",
    text: "Mango-Almond Smoothie",
    mainBackgroundColor:
      "bg-gradient-to-r from-yellow-darker from-50% to-yellow-light to-50% ",
    bgFill: "fill-yellow-light",
    logoFill: "fill-yellow-darker",
    hoverColor: "hover:bg-yellow-light",
    isFavorite: false,
    shadowBtnColor: "shadow-yellow-darker",
    textColor: "text-yellow-darker",
    className: "",
    content: [mango, pineapple, banana, coconut],
    nutritionalVal: ["209", "3g", "35g", "14g", "44mg"],
    price: "11.99",
    relatedSmoothies: [14, 15, 13],
  },
  {
    id: 14,
    src: yellowBowl2,
    alt: "mango blueberry bowl",
    borderColor: "border-yellow-darker",
    shadowColor: "max-md-tablet:shadow-[0_10px_20px_rgb(240,128,128)]",
    backgroundColor: "bg-yellow-darker",
    footerBackgroundColor: "md-tablet:bg-yellow-lightest",
    text: "Mango Blueberry Smoothie",
    mainBackgroundColor:
      "bg-gradient-to-r from-yellow-darker from-50% to-yellow-light to-50% ",
    bgFill: "fill-yellow-light",
    logoFill: "fill-yellow-darker",
    isFavorite: false,
    hoverColor: "hover:bg-yellow-light",
    shadowBtnColor: "shadow-yellow-darker",
    textColor: "text-yellow-darker",
    className: "",
    content: [mango, pineapple, blueberry, coconut],
    nutritionalVal: ["525", "12g", "109g", "8g", "262mg"],
    price: "8.75",
    relatedSmoothies: [13, 15, 14],
  },
  {
    id: 15,
    src: yellowBowl3,
    alt: "mango bowl",
    borderColor: "border-yellow-darker",
    shadowColor: "max-md-tablet:shadow-[0_10px_20px_rgb(240,128,128)]",
    backgroundColor: "bg-yellow-darker",
    footerBackgroundColor: "md-tablet:bg-yellow-lightest",
    text: "Mango Smoothie",
    mainBackgroundColor:
      "bg-gradient-to-r from-yellow-darker from-50% to-yellow-light to-50% ",
    bgFill: "fill-yellow-light",
    logoFill: "fill-yellow-darker",
    isFavorite: false,
    hoverColor: "hover:bg-yellow-light",
    shadowBtnColor: "shadow-yellow-darker",
    textColor: "text-yellow-darker",
    className: "",
    content: [mango, raspberry, banana, coconut],
    nutritionalVal: ["412", "26g", "47g", "4g", "179mg"],
    price: "7.99",
    relatedSmoothies: [13, 14, 15],
  },
];
