export type Smoothie = {
  src: string;
  alt: string;
  borderColor: string;
  shadowColor: string;
  backgroundColor: string;
  footerBackgroundColor: string;
  hoverColor: string;
  mainBackgroundColor: string;
  bgFill: string;
  logoFill: string;
  shadowBtnColor: String;
  text: string;
  textColor: string;
  className: string;
  content: string[];
  nutritionalVal: string[];
  price: string;
  relatedSmoothies: Smoothie[];
};
