export type Smoothie = {
  id: number;
  src: string;
  alt: string;
  borderColor: string;
  shadowColor: string;
  backgroundColor: string;
  footerBackgroundColor: string;
  hoverColor: string;
  mainBackgroundColor: string;
  bgFill: string;
  logoFill: string;
  shadowBtnColor: string;
  text: string;
  textColor: string;
  className: string;
  content: string[];
  isFavorite: boolean;
  nutritionalVal: string[];
  price: string;
  relatedSmoothies: number[];
};
